[build]
builder = "nixpacks"
buildCommand = "npm ci --include=dev && npm run build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[environments]
  [environments.production]
  PORT = "5000"
  NODE_ENV = "production"
  
  [environments.development]
  PORT = "5000"
  NODE_ENV = "development"

[[volumes]]
name = "uploads"
path = "/uploads"

