[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "node dist/index.js"

[nixpacks]
nodeVersion = "20"

[environments]
  [environments.production]
  PORT = "5000"
  NODE_ENV = "production"

